spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_SECRET}
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.howtodoinjava: ERROR
    org.hibernate:
      engine.internal: ERROR
      SQL: ERROR
      type.descriptor.sql.BasicBinder: ERROR

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

com:
  finance:
    barra:
      adminUsername: ${ADMIN_USERNAME}
      adminSecret: ${ADMIN_SECRET}